In [8]:
import numpy as np
from numpy.linalg import svd

In [3]:
X = np.array([[1, 1, 1, 0, 0], 
              [2, 2, 2, 0, 0], 
              [1, 1, 1, 0, 0], 
              [5, 5, 5, 0, 0], 
              [1, 1, 0, 2, 2], 
              [0, 0, 0, 3, 3], 
              [0, 0, 0, 1, 1]], dtype=np.float32)
print(X)

[[1. 1. 1. 0. 0.]
 [2. 2. 2. 0. 0.]
 [1. 1. 1. 0. 0.]
 [5. 5. 5. 0. 0.]
 [1. 1. 0. 2. 2.]
 [0. 0. 0. 3. 3.]
 [0. 0. 0. 1. 1.]]


In [4]:
mu = np.mean(X, axis=0)
X_norm = X - mu
print(X_norm)

[[-0.42857146 -0.42857146 -0.28571427 -0.85714287 -0.85714287]
 [ 0.57142854  0.57142854  0.71428573 -0.85714287 -0.85714287]
 [-0.42857146 -0.42857146 -0.28571427 -0.85714287 -0.85714287]
 [ 3.5714285   3.5714285   3.7142859  -0.85714287 -0.85714287]
 [-0.42857146 -0.42857146 -1.2857143   1.1428571   1.1428571 ]
 [-1.4285715  -1.4285715  -1.2857143   2.142857    2.142857  ]
 [-1.4285715  -1.4285715  -1.2857143   0.14285713  0.14285713]]


In [6]:
m = X.shape[0]
Sigma = (X_norm.T @ X_norm) / m
Sigma

array([[ 2.5306125,  2.5306125,  2.5918367, -0.9387755, -0.9387755],
       [ 2.5306125,  2.5306125,  2.5918367, -0.9387755, -0.9387755],
       [ 2.5918367,  2.5918367,  2.7755103, -1.1020408, -1.1020408],
       [-0.9387755, -0.9387755, -1.1020408,  1.2653061,  1.2653061],
       [-0.9387755, -0.9387755, -1.1020408,  1.2653061,  1.2653061]],
      dtype=float32)

In [9]:
U, S, V = svd(Sigma)
S

array([8.7173052e+00, 1.5831665e+00, 6.6876046e-02, 5.1563194e-16,
       0.0000000e+00], dtype=float32)

In [10]:
X_proj = X_norm @ U[:, :3]

print(X_proj)


[[ 0.16674255  1.3749475  -0.00915384]
 [-1.4442885   0.73902875 -0.02281802]
 [ 0.16674255  1.3749475  -0.00915384]
 [-6.2773814  -1.1687274  -0.0638108 ]
 [ 1.7595298  -1.1001502   0.57129437]
 [ 3.3326042  -1.9204675  -0.35202393]
 [ 2.2960503   0.7004216  -0.11433446]]


In [12]:
X_approx = X_proj @ U[:, :3].T + mu

print(X_approx)

[[ 1.0000000e+00  1.0000000e+00  1.0000000e+00 -5.9604645e-08
  -5.9604645e-08]
 [ 2.0000000e+00  2.0000000e+00  2.0000000e+00 -5.9604645e-08
  -5.9604645e-08]
 [ 1.0000000e+00  1.0000000e+00  1.0000000e+00 -5.9604645e-08
  -5.9604645e-08]
 [ 5.0000000e+00  5.0000000e+00  5.0000005e+00 -5.9604645e-08
  -5.9604645e-08]
 [ 1.0000001e+00  1.0000001e+00 -1.1920929e-07  2.0000000e+00
   2.0000000e+00]
 [ 1.1920929e-07  1.1920929e-07  0.0000000e+00  3.0000000e+00
   3.0000000e+00]
 [ 1.1920929e-07  1.1920929e-07  0.0000000e+00  1.0000000e+00
   1.0000000e+00]]


In [14]:
X


array([[1., 1., 1., 0., 0.],
       [2., 2., 2., 0., 0.],
       [1., 1., 1., 0., 0.],
       [5., 5., 5., 0., 0.],
       [1., 1., 0., 2., 2.],
       [0., 0., 0., 3., 3.],
       [0., 0., 0., 1., 1.]], dtype=float32)